Dad Jokes 🤓
emptycrown/llama-hub pull request #43
Opened 2023-02-16 17:25 UTC by SidU

Because agents shouldn't just search on Google/Bing for what dad jokes are when someone wants a dad-joke. They should respond with actual dad-jokes!

2023-02-16 17:30 UTC, emptycrown commented
This is amazing haha. I'm going to use this for testing stuff in the future.

2023-02-16 19:02 UTC, emptycrown requested changes

2023-02-16 19:02 UTC, emptycrown commented on loader_hub/dadjokes/base.py
> +"""icanhazdadjoke based dad-joke generator."""
Can we name this `dad_jokes` instead? Also, you'll need to add it to the `library.json` file for it to be picked up by `gpt_index.download_loader` or the website.

2023-02-16 19:02 UTC, emptycrown commented on loader_hub/dadjokes/base.py
> +            return "Sorry, I couldn't get a joke right now. Please try again later."
Let's throw an error here instead of returning something that actually gets turned into a Document

2023-02-17 06:09 UTC, SidU commented
@emptycrown addressed your feedback 🙂

2023-02-17 06:12 UTC, emptycrown approved these changes

2023-02-17 06:12 UTC, emptycrown commented
Thanks -- I think you forgot to change the directory to `dad_jokes` as well?

2023-02-17 06:19 UTC, SidU commented
> Thanks -- I think you forgot to change the directory to `dad_jokes` as well?

Yes, just pushed a fix.

2023-02-17 06:45 UTC, merged