Upodate for MongoDB Atlast
emptycrown/llama-hub pull request #71
Opened 2023-02-28 09:07 UTC by Rishav-hub

Previously class took `host` and `port` as a parameter. Connect with MongoDB Atlas it's not possible to provide the host and port as it has a single URL. So directly pass the URL to the MongoClient.

2023-02-28 09:08 UTC, Rishav-hub commented
@emptycrown

2023-02-28 16:45 UTC, emptycrown requested changes
Good catch. How about we make it so both options are usable? So `url` is a new `Optional[str]` and it uses that arg if host/port isn't available.

2023-02-28 16:45 UTC, emptycrown commented on loader_hub/mongo/base.py
> +        mongo_db_url (str): Mongo Full URL.
how about just db_url or url?

2023-03-01 04:59 UTC, Rishav-hub reviewed
Yes that would also work.

2023-03-11 00:39 UTC, jerryjliu commented
hi @Rishav-hub, are you able to get to this? if not i can help land

2023-03-11 06:40 UTC, Rishav-hub commented on loader_hub/mongo/base.py
> +        mongo_db_url (str): Mongo Full URL.
db_url would work

2023-03-11 07:04 UTC, Rishav-hub commented
> hi @Rishav-hub, are you able to get to this? if not i can help land

Actually little confused where can I again change the code in this pull request.

2023-03-11 07:06 UTC, jerryjliu commented
> > hi @Rishav-hub, are you able to get to this? if not i can help land
> 
> Actually little confused where can I again change the code in this pull request.

as in, keep the host/port parameters, and set mongo_db_url as an Optional string. if mongo_db_url is specified use that, otherwise use host and port

2023-03-11 08:00 UTC, Rishav-hub reviewed
added condition for mongodb url.

2023-03-11 08:15 UTC, jerryjliu approved these changes

2023-03-14 01:22 UTC, emptycrown approved these changes

2023-03-14 01:26 UTC, merged