add zendesk, intercom, and wordpress API loaders
emptycrown/llama-hub pull request #84
Opened 2023-03-05 21:06 UTC by bborn

@jerryjliu  here's a PR for Zendesk, Intercom, and Wordpress loaders.

2023-03-06 00:16 UTC, jerryjliu requested changes
thanks for adding these! 

note: you'll want to add to library.json as well (and the comments about lazy importing will be more relevant then)

2023-03-06 00:16 UTC, jerryjliu commented on loader_hub/intercom/base.py
> +from bs4 import BeautifulSoup
you may have to do lazy importing of bs4 for tests to pass. see `loader_hub/web/beautiful_soup_web/base.py` as an example 

(i know it's pretty hacky)

2023-03-06 00:16 UTC, jerryjliu commented on loader_hub/wordpress/base.py
> +from bs4 import BeautifulSoup
same here

2023-03-06 00:16 UTC, jerryjliu commented on loader_hub/zendesk/base.py
> +from bs4 import BeautifulSoup
same here

2023-03-06 17:51 UTC, bborn commented
@jerryjliu ok, I *think* I did what you wanted. I can't run the tests locally for some reason (I get `E   KeyError: PosixPath('/Users/bruno/Projects/python/llama-hub')`) which I don't understand

2023-03-07 00:45 UTC, jerryjliu approved these changes
looks good!

> @jerryjliu ok, I _think_ I did what you wanted. I can't run the tests locally for some reason (I get `E KeyError: PosixPath('/Users/bruno/Projects/python/llama-hub')`) which I don't understand

are you just doing `pytest tests` from within your llama-hub fork? i cloned your repo and it's working for me

2023-03-07 00:45 UTC, merged