gmail reader
emptycrown/llama-hub pull request #92
Opened 2023-03-08 01:06 UTC by bborn

Add a document loader for gmail

2023-03-08 07:58 UTC, jerryjliu requested changes
this looks great! 

i'd fill out the README.md and requirements.txt (seems like there's googleapiclient deps and bs4 deps

2023-03-08 07:58 UTC, jerryjliu commented on loader_hub/gmail/base.py
> +from googleapiclient.discovery import build
would include as a lazy import

2023-03-08 11:24 UTC, bborn commented on loader_hub/gmail/base.py
> +from googleapiclient.discovery import build
Done

2023-03-08 17:43 UTC, jerryjliu approved these changes
thanks! approving to unblock

2023-03-08 17:43 UTC, jerryjliu commented on loader_hub/gmail/README.md
> +GoogleDocsReader = download_loader('GmailReader')
nit: GmailReader

2023-03-08 17:43 UTC, jerryjliu commented on loader_hub/gmail/README.md
> +GoogleDocsReader = download_loader('GmailReader')
nit: Gmail (also if you want you could just remove the LlamaIndex and Langchain sections to make the readme more concise)

2023-03-08 17:43 UTC, jerryjliu commented on loader_hub/gmail/base.py
> +            number_of_results (Optional[int]): the number of events to return. Defaults to 100.
these aren't arguments in the load_data function, I would remove

2023-03-10 16:34 UTC, jerryjliu approved these changes

2023-03-12 03:08 UTC, merged